### ISSUE TITLE
Link in text can cause crash

### ISSUE THREAD

**Issue by samskiter** [NimbusKit/markdown#20]
We had the following text in markdown:

```
If not, see <http://www.gnu.org/licenses/>.
```

This was recognised as an URL, but NRURL url with string returned nil. this causes an exception to be thrown in addLinksToAttributedString

**Comment by NachoSoto** [comment]
Yeah, this was introduced here: https://github.com/NimbusKit/markdown/pull/18.
The bug was already there, but you could work around it by ignoring nil URLs.

**Comment by jverkoey** [comment]
Ah, interesting problem. Will make a quick modification to avoid adding nil entries.
